version: "3"
services:
  aeternity_uat:
    image: aeternity/aeternity:v3.0.1
    container_name: aeternity_uat
    environment:
      - EPOCH_CONFIG=/home/aeternity/aeternity.yaml
    volumes:
    #    /Users/alekseytsekov/Documents/projects/aeternity/test-state-demo/state-testnet/StateChannelsBar/docker/test-net-config.yaml
      - ~/Documents/projects/aeternity/test-state-demo/base-aepp-state-channel-demo/StateChannelsBar/docker/test-net-config.yaml:/home/aeternity/aeternity.yaml
      - ~/Documents/projects/aeternity/test-state-demo/base-aepp-state-channel-demo/StateChannelsBar/docker/db-testnet-new:/home/aeternity/node/data/mnesia
      - ~/Documents/projects/aeternity/test-state-demo/base-aepp-state-channel-demo/StateChannelsBar/docker/logs:/home/aeternity/node/log
    ports:
      - "3013:3013"
      - "3014:3014"
      - "3113:3113"
      # - "3015:3015"
      - "3333:3333"

  # proxy:
  #   image: nginx:1.13.8
  #   hostname: proxy
  #   ports:
  #     - "3113:3113"
  #     - "3015:3015"
  #     - "3333:3333"

  #   volumes:
  #     - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
  #     - ./docker/nginx-cors.conf:/etc/nginx/cors.conf
  #     - ./docker/nginx-ws.conf:/etc/nginx/ws.conf